<?php

namespace Caravane\Bundle\OrganicBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class Planning2offreController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Caravane\Bundle\OrganicBundle\Controller\Planning2offreController();
        return $instance;
    }
}
