<?php

namespace Caravane\CalendarBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CalendarController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Caravane\CalendarBundle\Controller\CalendarController();
        return $instance;
    }
}
