<?php

namespace Caravane\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function listAll($type=null,$ob=null,$page=1) {
        $dql = "SELECT C FROM CaravaneUserBundle:User C ";
        //$dql.=" WHERE 1=1 ";

        if($ob) {
            $dql.=" ORDER BY C.".$ob." ";
        }

        $query = $this->getEntityManager()->createQuery($dql)
                       ->setFirstResult(($page-1)*25)
                       ->setMaxResults(25);

        $entities = new Paginator($query, $fetchJoinCollection = true);


        //return array('entities'=>$paginator);
        return $entities;
    }
}
