<?php

namespace Proxies\__CG__\Caravane\Bundle\OrganicBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offre extends \Caravane\Bundle\OrganicBundle\Entity\Offre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'eventdate', 'insertdate', 'updatedate', 'reference', 'offretype', 'planningcomments', 'offrecomments', 'surface', 'startbuild', 'endbuild', 'requestdate', 'status', 'pricetype', 'price', 'pricecomments', 'conditions', 'conditionsslices', 'tents', 'tentscomments', 'address', 'number', 'zip', 'city', 'country', 'contact', 'phone', 'phone2', 'mobile', 'fax', 'email', 'url', 'comments', 'introtext', 'issue', 'deleted', 'public', 'language', 'validity', 'userid', 'clientid', 'jobid', 'tents2offre', 'transport2offre', 'plannings', 'products', 'condition', 'slices', 'totalSlice', 'totalSlicePriceht', 'document', 'files', 'comment');
        }

        return array('__isInitialized__', 'id', 'eventdate', 'insertdate', 'updatedate', 'reference', 'offretype', 'planningcomments', 'offrecomments', 'surface', 'startbuild', 'endbuild', 'requestdate', 'status', 'pricetype', 'price', 'pricecomments', 'conditions', 'conditionsslices', 'tents', 'tentscomments', 'address', 'number', 'zip', 'city', 'country', 'contact', 'phone', 'phone2', 'mobile', 'fax', 'email', 'url', 'comments', 'introtext', 'issue', 'deleted', 'public', 'language', 'validity', 'userid', 'clientid', 'jobid', 'tents2offre', 'transport2offre', 'plannings', 'products', 'condition', 'slices', 'totalSlice', 'totalSlicePriceht', 'document', 'files', 'comment');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Offre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', array());

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiles($files)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiles', array($files));

        return parent::setFiles($files);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsertdate($insertdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsertdate', array($insertdate));

        return parent::setInsertdate($insertdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsertdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsertdate', array());

        return parent::getInsertdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedate($updatedate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedate', array($updatedate));

        return parent::setUpdatedate($updatedate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedate', array());

        return parent::getUpdatedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', array($reference));

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', array());

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffretype($offretype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffretype', array($offretype));

        return parent::setOffretype($offretype);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffretype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffretype', array());

        return parent::getOffretype();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanningcomments($planningcomments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanningcomments', array($planningcomments));

        return parent::setPlanningcomments($planningcomments);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanningcomments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanningcomments', array());

        return parent::getPlanningcomments();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffrecomments($offrecomments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffrecomments', array($offrecomments));

        return parent::setOffrecomments($offrecomments);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffrecomments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffrecomments', array());

        return parent::getOffrecomments();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurface($surface)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurface', array($surface));

        return parent::setSurface($surface);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurface()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurface', array());

        return parent::getSurface();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartbuild($startbuild)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartbuild', array($startbuild));

        return parent::setStartbuild($startbuild);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartbuild()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartbuild', array());

        return parent::getStartbuild();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndbuild($endbuild)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndbuild', array($endbuild));

        return parent::setEndbuild($endbuild);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndbuild()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndbuild', array());

        return parent::getEndbuild();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequestdate($requestdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequestdate', array($requestdate));

        return parent::setRequestdate($requestdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestdate', array());

        return parent::getRequestdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricetype($pricetype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricetype', array($pricetype));

        return parent::setPricetype($pricetype);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricetype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricetype', array());

        return parent::getPricetype();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricecomments($pricecomments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricecomments', array($pricecomments));

        return parent::setPricecomments($pricecomments);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricecomments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricecomments', array());

        return parent::getPricecomments();
    }

    /**
     * {@inheritDoc}
     */
    public function setConditions($conditions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConditions', array($conditions));

        return parent::setConditions($conditions);
    }

    /**
     * {@inheritDoc}
     */
    public function getConditions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConditions', array());

        return parent::getConditions();
    }

    /**
     * {@inheritDoc}
     */
    public function setConditionsslices($conditionsslices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConditionsslices', array($conditionsslices));

        return parent::setConditionsslices($conditionsslices);
    }

    /**
     * {@inheritDoc}
     */
    public function getConditionsslices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConditionsslices', array());

        return parent::getConditionsslices();
    }

    /**
     * {@inheritDoc}
     */
    public function setTents($tents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTents', array($tents));

        return parent::setTents($tents);
    }

    /**
     * {@inheritDoc}
     */
    public function getTents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTents', array());

        return parent::getTents();
    }

    /**
     * {@inheritDoc}
     */
    public function setTentscomments($tentscomments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTentscomments', array($tentscomments));

        return parent::setTentscomments($tentscomments);
    }

    /**
     * {@inheritDoc}
     */
    public function getTentscomments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTentscomments', array());

        return parent::getTentscomments();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', array($number));

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', array());

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip($zip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', array($zip));

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', array());

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone2($phone2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone2', array($phone2));

        return parent::setPhone2($phone2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone2', array());

        return parent::getPhone2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments($comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', array($comments));

        return parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', array());

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntrotext($introtext)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntrotext', array($introtext));

        return parent::setIntrotext($introtext);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntrotext()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntrotext', array());

        return parent::getIntrotext();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssue($issue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssue', array($issue));

        return parent::setIssue($issue);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssue', array());

        return parent::getIssue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublic($public)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublic', array($public));

        return parent::setPublic($public);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublic', array());

        return parent::getPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', array($language));

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', array());

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCopyid($copyid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCopyid', array($copyid));

        return parent::setCopyid($copyid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCopyid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCopyid', array());

        return parent::getCopyid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid(\Caravane\UserBundle\Entity\User $userid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', array($userid));

        return parent::setUserid($userid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', array());

        return parent::getUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientid(\Caravane\Bundle\OrganicBundle\Entity\Client $clientid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientid', array($clientid));

        return parent::setClientid($clientid);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientid', array());

        return parent::getClientid();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobid(\Caravane\Bundle\OrganicBundle\Entity\Job $jobid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobid', array($jobid));

        return parent::setJobid($jobid);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobid', array());

        return parent::getJobid();
    }

    /**
     * {@inheritDoc}
     */
    public function addTents2offre(\Caravane\Bundle\OrganicBundle\Entity\Tent2offre $tents2offre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTents2offre', array($tents2offre));

        return parent::addTents2offre($tents2offre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTents2offre(\Caravane\Bundle\OrganicBundle\Entity\Tent2offre $tents2offre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTents2offre', array($tents2offre));

        return parent::removeTents2offre($tents2offre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTents2offre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTents2offre', array());

        return parent::getTents2offre();
    }

    /**
     * {@inheritDoc}
     */
    public function addPlanning(\Caravane\Bundle\OrganicBundle\Entity\Planning2offre $plannings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPlanning', array($plannings));

        return parent::addPlanning($plannings);
    }

    /**
     * {@inheritDoc}
     */
    public function removePlanning(\Caravane\Bundle\OrganicBundle\Entity\Planning2offre $plannings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlanning', array($plannings));

        return parent::removePlanning($plannings);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlannings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlannings', array());

        return parent::getPlannings();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\Caravane\Bundle\OrganicBundle\Entity\Product2offre $products)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', array($products));

        return parent::addProduct($products);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\Caravane\Bundle\OrganicBundle\Entity\Product2offre $products)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', array($products));

        return parent::removeProduct($products);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', array());

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addSlice(\Caravane\Bundle\OrganicBundle\Entity\Slice2offre $slices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSlice', array($slices));

        return parent::addSlice($slices);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSlice(\Caravane\Bundle\OrganicBundle\Entity\Slice2offre $slices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSlice', array($slices));

        return parent::removeSlice($slices);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlices', array());

        return parent::getSlices();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalSlice($totalSlice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalSlice', array($totalSlice));

        return parent::setTotalSlice($totalSlice);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalSlice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalSlice', array());

        return parent::getTotalSlice();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalSlicePriceht($totalSlicePriceht)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalSlicePriceht', array($totalSlicePriceht));

        return parent::setTotalSlicePriceht($totalSlicePriceht);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalSlicePriceht()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalSlicePriceht', array());

        return parent::getTotalSlicePriceht();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidity($validity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidity', array($validity));

        return parent::setValidity($validity);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidity', array());

        return parent::getValidity();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventdate($eventdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventdate', array($eventdate));

        return parent::setEventdate($eventdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventdate', array());

        return parent::getEventdate();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocument(\Caravane\Bundle\OrganicBundle\Entity\Document $document)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocument', array($document));

        return parent::addDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocument(\Caravane\Bundle\OrganicBundle\Entity\Document $document)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocument', array($document));

        return parent::removeDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocument', array());

        return parent::getDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function addComment(\Caravane\Bundle\OrganicBundle\Entity\Comment $comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComment', array($comment));

        return parent::addComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComment(\Caravane\Bundle\OrganicBundle\Entity\Comment $comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComment', array($comment));

        return parent::removeComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', array());

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function addTransport2offre(\Caravane\Bundle\OrganicBundle\Entity\Transport2offre $transport2offre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTransport2offre', array($transport2offre));

        return parent::addTransport2offre($transport2offre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTransport2offre(\Caravane\Bundle\OrganicBundle\Entity\Transport2offre $transport2offre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTransport2offre', array($transport2offre));

        return parent::removeTransport2offre($transport2offre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransport2offre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransport2offre', array());

        return parent::getTransport2offre();
    }

    /**
     * {@inheritDoc}
     */
    public function addCondition(\Caravane\Bundle\OrganicBundle\Entity\Condition $condition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCondition', array($condition));

        return parent::addCondition($condition);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCondition(\Caravane\Bundle\OrganicBundle\Entity\Condition $condition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCondition', array($condition));

        return parent::removeCondition($condition);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondition', array());

        return parent::getCondition();
    }

}
