CaravaneOrganicBundle_homepage:
    pattern:  /
    defaults: { _controller: CaravaneOrganicBundle:Dashboard:index }

CaravaneOrganicBundle_client:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/client.yml"
    prefix:   /client

CaravaneOrganicBundle_tent:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/tent.yml"
    prefix:   /stock

CaravaneOrganicBundle_offre:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/offre.yml"
    prefix:   /offer

CaravaneOrganicBundle_invoice:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/invoice.yml"
    prefix:   /invoice

CaravaneOrganicBundle_job:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/job.yml"
    prefix:   /job

CaravaneOrganicBundle_planning:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/planning.yml"
    prefix:   /planning

CaravaneOrganicBundle_dashboard:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/dashboard.yml"
    prefix:   /

CaravaneOrganicBundle_transport:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/transport.yml"
    prefix:   /transport

CaravaneOrganicBundle_search:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/search.yml"
    prefix:   /

caravane_calendar:
    resource: "@CaravaneCalendarBundle/Resources/config/routing.yml"
