CaravaneOrganicBundle_homepage:
    pattern:  /
    defaults: { _controller: CaravaneOrganicBundle:Default:index }

CaravaneOrganicBundle_client:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/client.yml"
    prefix:   /client

CaravaneOrganicBundle_tent:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/tent.yml"
    prefix:   /stock

CaravaneOrganicBundle_offre:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/offre.yml"
    prefix:   /offre

CaravaneOrganicBundle_invoice:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/invoice.yml"
    prefix:   /invoice

CaravaneOrganicBundle_job:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/job.yml"
    prefix:   /job

CaravaneOrganicBundle_planning:
    resource: "@CaravaneOrganicBundle/Resources/config/routing/planning.yml"
    prefix:   /planning

