parameters:
    caravane_organic.client.class: Caravane\Bundle\OrganicBundle\Managers\ClientManager

services:
    caravane_organic.client_manager:
        class: %caravane_organic.client.class%
        arguments: [client,em]