parameters:
    caravane_organic.client.class: Caravane\Bundle\OrganicBundle\Managers\ClientManager
    caravane_organic.invoice.class: Caravane\Bundle\OrganicBundle\Managers\InvoiceManager
    caravane_organic.offre.class: Caravane\Bundle\OrganicBundle\Managers\OffreManager
    caravane_organic.document.class: Caravane\Bundle\OrganicBundle\Managers\DocumentManager
    caravane_organic.pdf.class: Caravane\Bundle\OrganicBundle\Managers\PdfManager
    caravane_organic.listener.class: Caravane\Bundle\OrganicBundle\Listeners\EntitiesStatusUpdater

services:
    caravane_organic.client_manager:
        class: %caravane_organic.client.class%
        arguments: [client,em]


    caravane_organic.invoice_manager:
        class: %caravane_organic.invoice.class%
        arguments: [invoice,em]

    caravane_organic.offre_manager:
        class: %caravane_organic.offre.class%
        arguments: [offre,em]

    caravane_organic.pdf_manager:
        class: %caravane_organic.pdf.class%
        arguments: [em,@templating,@html2pdf]

    caravane_organic.document_manager:
        class: %caravane_organic.document.class%
        arguments: [entity,em]


    caravane_organic.listener:
        class: %caravane_organic.listener.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }


#    fos_elastica.index.website.invoice
#        class:






#<service id="acme.search_provider.user" class="Acme\UserBundle\Search\UserProvider">
#        <tag name="fos_elastica.provider" index="website" type="user" />
#        <argument type="service" id="fos_elastica.index.website.user" />
#    </service>
