parameters:
#    caravane_organic.example.class: Caravane\Bundle\OrganicBundle\Example

services:
#    caravane_organic.example:
#        class: %caravane_organic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
