imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../src/Caravane/UIBundle/Resources/config/config.yml }
    - { resource: ../../src/Caravane/Bundle/BIJUploadBundle/Resources/config/config.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:  "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        sass:    ~
        compass: ~
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Caravane\UserBundle\Entity\User


fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        appli:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            my_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [mynGram]
                        filter:
                            mynGram:
                                type: nGram
                                min_gram: 1
                                max_gram: 10
            types:
                invoice:
                    mappings:
                        lastname: { boost: 5, analyzer: my_analyzer }
                        firstName: { boost: 3, analyzer: my_analyzer  }
                        name: { boost: 5, analyzer: my_analyzer  }
                        reference: { boost: 5 }
                        priceht: { boost: 3 }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model: Caravane\Bundle\OrganicBundle\Entity\Invoice
                        provider: ~
                        #listener: ~
                        finder: ~





