imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../src/Caravane/UIBundle/Resources/config/config.yml }
    - { resource: ../../src/Caravane/Bundle/BIJUploadBundle/Resources/config/config.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:  "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    assets:
        font-awesome-otf:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/FontAwesome.otf'
            output: 'css/fonts/FontAwesome.otf'
        font-awesome-eot:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.eot'
            output: 'css/fonts/fontawesome-webfont.eot'
        font-awesome-svg:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.svg'
            output: 'css/fonts/fontawesome-webfont.svg'
        font-awesome-ttf:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.ttf'
            output: 'css/fonts/fontawesome-webfont.ttf'
        font-awesome-woff:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff'
            output: 'css/fonts/fontawesome-webfont.woff'
        glyphicons-halflings-regular-eot:
            inputs: '%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.eot'
            output: 'css/fonts/glyphicons-halflings-regular.eot'
        glyphicons-halflings-regular-ttf:
            inputs: '%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.ttf'
            output: 'css/fonts/glyphicons-halflings-regular.ttf'
        glyphicons-halflings-regular-svg:
            inputs: '%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.svg'
            output: 'css/fonts/glyphicons-halflings-regular.svg'
        glyphicons-halflings-regular-woff:
            inputs: '%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.woff'
            output: 'css/fonts/glyphicons-halflings-regular.woff'
    #java: /usr/bin/java
    filters:
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        less: # Nous importons ici nos variables
            node: %node_bin%
            node_paths: [%node_modules%]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    host:           "%mailer_host%"
    username:       "%mailer_user%"
    password:       "%mailer_password%"
    transport:      "%mailer_transport%"
    port:           "%mailer_port%"
    encryption:     "%mailer_encryption%"
    auth_mode:     "%mailer_auth_mode%"

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Caravane\UserBundle\Entity\User


fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        appli:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            my_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [mynGram]
                        filter:
                            mynGram:
                                type: nGram
                                min_gram: 1
                                max_gram: 10
            types:
                invoice:
                    mappings:
                        lastname: { boost: 5, analyzer: my_analyzer }
                        firstName: { boost: 3, analyzer: my_analyzer  }
                        name: { boost: 5, analyzer: my_analyzer  }
                        reference: { boost: 5 }
                        priceht: { boost: 3 }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model: Caravane\Bundle\OrganicBundle\Entity\Invoice
                        provider: ~
                        #listener: ~
                        finder: ~

#jms_translation:
#    configs:
#        app:
#            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
#            output_dir: %kernel.root_dir%/Resources/translations
#            ignored_domains: [routes]
#            excluded_names: [*TestCase.php, *Test.php]
#            excluded_dirs: [cache, data, logs]


ivory_ck_editor:
    configs:
        minimum:
            toolbar: "minimum"

    toolbars:
        configs:
            minimum: [ "@editing", "/", "@basicstyles" , "/", "@paragraph" ]
        items:
            editing: [ 'find', 'selection', 'spellchecker' ]
            basicstyles:     [ 'basicstyles', 'cleanup' ]
            paragraph:     [ 'list', 'indent', 'blocks', 'align' ]

