jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /login_check
                login_path: /login
                default_target_path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, role: ROLE_USER }
        - { path: ^/offer, role: ROLE_USER }
        - { path: ^/job, role: ROLE_USER }
        - { path: ^/invoice, role: ROLE_USER }
        - { path: ^/planning, role: ROLE_USER }
        - { path: ^/stock, role: ROLE_USER }
        - { path: ^/transport, role: ROLE_USER }
        - { path: ^/client, role: ROLE_USER }
        - { path: ^/user, role: ROLE_USER }


        

