<?php

namespace Caravane\Bundle\OrganicBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{

	public function listAll($type=null,$ob=null,$page=1) {
		$dql = "SELECT C FROM CaravaneOrganicBundle:Client C ";
		$dql.=" WHERE C.public=1 ";
		if($type) {
			switch($type) {
				case 'owner':
					$dql.=" AND SIZE(C.tents) > 0 ";
				break;
				case 'renter':
					$dql.=" AND SIZE(C.tents) = 0 ";
				break;

				default:
					$dql.=" AND C.clienttype='".$type."' ";
				break;
			}
			
		}
		if($ob) {
			$dql.=" ORDER BY C.".$ob." ";
		}

		$query = $this->getEntityManager()->createQuery($dql)
                       ->setFirstResult(($page-1)*25)
                       ->setMaxResults(25);

		$entities = new Paginator($query, $fetchJoinCollection = true);


		//return array('entities'=>$paginator);
		return $entities;
	}

	public function autocomplete($keyword,$type="json") {

		$query = $this->getEntityManager()->createQuery("SELECT C FROM CaravaneOrganicBundle:Client C WHERE C.name LIKE ?1 OR C.firstname LIKE ?1 OR C.lastname LIKE ?1");
		$query->setParameter(1,  '%'.strtolower($keyword).'%');
			
		$result=$query->getResult();
		$clients=array();
		foreach($result as $client) {
			if(!$name=$client->getName()) {
				$name=$client->getFirstname()." ".$client->getLastname();
			}
			$clients[]=array('value'=>$client->getId(),"label"=>$name);
		}
		switch($type) {
			default:
			case 'json':
				return json_encode($clients);
			break;
		}
		
	}
}
