<?php

namespace Proxies\__CG__\Caravane\Bundle\OrganicBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tent2job extends \Caravane\Bundle\OrganicBundle\Entity\Tent2job implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'etat', 'plancher', 'surfaceplancher', 'sol', 'canalisation', 'other', 'jobid', 'offreid', 'tentid');
        }

        return array('__isInitialized__', 'id', 'etat', 'plancher', 'surfaceplancher', 'sol', 'canalisation', 'other', 'jobid', 'offreid', 'tentid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tent2job $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlancher($plancher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlancher', array($plancher));

        return parent::setPlancher($plancher);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlancher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlancher', array());

        return parent::getPlancher();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurfaceplancher($surfaceplancher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurfaceplancher', array($surfaceplancher));

        return parent::setSurfaceplancher($surfaceplancher);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurfaceplancher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurfaceplancher', array());

        return parent::getSurfaceplancher();
    }

    /**
     * {@inheritDoc}
     */
    public function setSol($sol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSol', array($sol));

        return parent::setSol($sol);
    }

    /**
     * {@inheritDoc}
     */
    public function getSol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSol', array());

        return parent::getSol();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanalisation($canalisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanalisation', array($canalisation));

        return parent::setCanalisation($canalisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanalisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanalisation', array());

        return parent::getCanalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setOther($other)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOther', array($other));

        return parent::setOther($other);
    }

    /**
     * {@inheritDoc}
     */
    public function getOther()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOther', array());

        return parent::getOther();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobid(\Caravane\Bundle\OrganicBundle\Entity\Job $jobid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobid', array($jobid));

        return parent::setJobid($jobid);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobid', array());

        return parent::getJobid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffreid(\Caravane\Bundle\OrganicBundle\Entity\Offre $offreid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffreid', array($offreid));

        return parent::setOffreid($offreid);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffreid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffreid', array());

        return parent::getOffreid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTentid(\Caravane\Bundle\OrganicBundle\Entity\Tent $tentid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTentid', array($tentid));

        return parent::setTentid($tentid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTentid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTentid', array());

        return parent::getTentid();
    }

}
