invoice:
    pattern:  /
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:index" }
    options:
        expose: true

invoice_show:
    pattern:  /{id}/show
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:show" }

invoice_pdf:
    pattern:  /{_locale}/{id}/pdf/{type}
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:pdf" }

invoice_new_from_job:
    pattern:  /newfromjob/{id}
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:newFromJob" }

invoice_sort_products:
    pattern: /{id}/sort_products
    defaults: {_controller: "CaravaneOrganicBundle:Invoice:sortProducts" }
    requirements: { _method: post }

invoice_add_transport:
    pattern:  /{id}/add_transport_product/{transportid}
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:addTransportProduct" }
    options:
        expose: true

invoice_add_product:
    pattern:  /{id}/add_product
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:addProduct" }
    options:
        expose: true


invoice_new:
    pattern:  /new
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:new" }

invoice_create:
    pattern:  /create
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:create" }
    requirements: { _method: post }

invoice_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:edit" }

invoice_update:
    pattern:  /{id}/update
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:update" }
    requirements: { _method: post }

invoice_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:delete" }
    requirements: { _method: post }

invoice_remove_product:
    pattern:  /{id}/remove_product/{productid}
    defaults: { _controller: "CaravaneOrganicBundle:Invoice:removeProduct" }
    requirements: { _method: post }
    options:
        expose: true

