job:
    pattern:  /
    defaults: { _controller: "CaravaneOrganicBundle:Job:index" }
    options:
        expose: true

job_show:
    pattern:  /{id}/show
    defaults: { _controller: "CaravaneOrganicBundle:Job:show" }

job_new:
    pattern:  /new
    defaults: { _controller: "CaravaneOrganicBundle:Job:new" }

job_create:
    pattern:  /create
    defaults: { _controller: "CaravaneOrganicBundle:Job:create" }
    requirements: { _method: post }

job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CaravaneOrganicBundle:Job:edit" }

job_update:
    pattern:  /{id}/update
    defaults: { _controller: "CaravaneOrganicBundle:Job:update" }
    requirements: { _method: post }

job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CaravaneOrganicBundle:Job:delete" }
    requirements: { _method: post }

job_remove_product:
    pattern:  /{id}/remove_product/{productid}
    defaults: { _controller: "CaravaneOrganicBundle:Job:removeProduct" }
    requirements: { _method: post }
    options:
        expose: true

job_add_tent:
    pattern:  /{id}/add_stock_product/{tentid}
    defaults: { _controller: "CaravaneOrganicBundle:Job:addStockProduct" }
    requirements: { _method: post }
    options:
        expose: true

job_slice_remove_product:
    pattern:  /{id}/remove_slice/{productid}
    defaults: { _controller: "CaravaneOrganicBundle:Job:removeSlice" }
    requirements: { _method: post }
    options:
        expose: true