offre:
    pattern:  /
    defaults: { _controller: "CaravaneOrganicBundle:Offre:index" }
    options:
        expose: true

offre_show:
    pattern:  /{id}/show
    defaults: { _controller: "CaravaneOrganicBundle:Offre:show" }

offre_new:
    pattern:  /new
    defaults: { _controller: "CaravaneOrganicBundle:Offre:new" }

offre_pdf:
    pattern:  /{_locale}/{id}/pdf
    defaults: { _controller: "CaravaneOrganicBundle:Offre:pdf" }



offre_create:
    pattern:  /create
    defaults: { _controller: "CaravaneOrganicBundle:Offre:create" }
    requirements: { _method: post }

offre_export:
    pattern:  /export
    defaults: { _controller: "CaravaneOrganicBundle:Offre:export" }

offre_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CaravaneOrganicBundle:Offre:edit" }

offre_duplicate:
    pattern:  /{id}/duplicate
    defaults: { _controller: "CaravaneOrganicBundle:Offre:duplicate" }

offre_update:
    pattern:  /{id}/update
    defaults: { _controller: "CaravaneOrganicBundle:Offre:update" }
    requirements: { _method: post }

offre_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CaravaneOrganicBundle:Offre:delete" }
    requirements: { _method: post }

offre_cancel:
    pattern:  /{id}/cancel
    defaults: { _controller: "CaravaneOrganicBundle:Offre:cancel" }
    requirements: { _method: get }
    options:
        expose: true

offre_remove_product:
    pattern:  /{id}/remove_product/{productid}
    defaults: { _controller: "CaravaneOrganicBundle:Offre:removeProduct" }
    requirements: { _method: post }
    options:
        expose: true

offre_add_tent:
    pattern:  /{id}/add_stock_product/{tentid}
    defaults: { _controller: "CaravaneOrganicBundle:Offre:addStockProduct" }
    requirements: { _method: post }
    options:
        expose: true

offre_add_transport:
    pattern:  /{id}/add_transport_product/{transportid}
    defaults: { _controller: "CaravaneOrganicBundle:Offre:addTransportProduct" }
    options:
        expose: true

offre_add_product:
    pattern:  /{id}/add_product
    defaults: { _controller: "CaravaneOrganicBundle:Offre:addProduct" }
    options:
        expose: true

offre_slice_remove_product:
    pattern:  /{id}/remove_slice/{productid}
    defaults: { _controller: "CaravaneOrganicBundle:Offre:removeSlice" }
    requirements: { _method: post }
    options:
        expose: true
offre_sort_products:
    pattern: /{id}/sort_products
    defaults: {_controller: "CaravaneOrganicBundle:Offre:sortProducts" }
    requirements: { _method: post }

offre_resolve:
    pattern:  /resolve
    defaults: { _controller: "CaravaneOrganicBundle:Offre:resolveIssue" }
    requirements: { _method: get }

offre_resolve_confirm:
    pattern:  /resolve/confirm
    defaults: { _controller: "CaravaneOrganicBundle:Offre:resolveConfirm" }

offre_remove_document:
    pattern:  /{id}/remove_document/{documentid}
    defaults: { _controller: "CaravaneOrganicBundle:Offre:removeDocument" }
    requirements: { _method: post }
    options:
        expose: true
