offre:
    pattern:  /
    defaults: { _controller: "CaravaneOrganicBundle:Offre:index" }
    options:
        expose: true

offre_show:
    pattern:  /{id}/show
    defaults: { _controller: "CaravaneOrganicBundle:Offre:show" }

offre_new:
    pattern:  /new
    defaults: { _controller: "CaravaneOrganicBundle:Offre:new" }

offre_pdf:
    pattern:  /{_locale}/{id}/pdf
    defaults: { _controller: "CaravaneOrganicBundle:Offre:pdf" }



offre_create:
    pattern:  /create
    defaults: { _controller: "CaravaneOrganicBundle:Offre:create" }
    requirements: { _method: post }

offre_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CaravaneOrganicBundle:Offre:edit" }

offre_update:
    pattern:  /{id}/update
    defaults: { _controller: "CaravaneOrganicBundle:Offre:update" }
    requirements: { _method: post }

offre_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CaravaneOrganicBundle:Offre:delete" }
    requirements: { _method: post }

offre_remove_product:
    pattern:  /{id}/remove_product/{productid}
    defaults: { _controller: "CaravaneOrganicBundle:Offre:removeProduct" }
    requirements: { _method: post }
    options:
        expose: true

offre_add_tent:
    pattern:  /{id}/add_stock_product/{tentid}
    defaults: { _controller: "CaravaneOrganicBundle:Offre:addStockProduct" }
    requirements: { _method: post }
    options:
        expose: true

offre_slice_remove_product:
    pattern:  /{id}/remove_slice/{productid}
    defaults: { _controller: "CaravaneOrganicBundle:Offre:removeSlice" }
    requirements: { _method: post }
    options:
        expose: true

offre_resolve:
    pattern:  /resolve
    defaults: { _controller: "CaravaneOrganicBundle:Offre:resolveIssue" }
    requirements: { _method: get }

offre_resolve_confirm:
    pattern:  /resolve/confirm
    defaults: { _controller: "CaravaneOrganicBundle:Offre:resolveConfirm" }

