planning:
    pattern:  /
    defaults: { _controller: "CaravaneOrganicBundle:Planning:index" }

planning_show:
    pattern:  /{id}/show
    defaults: { _controller: "CaravaneOrganicBundle:Planning:show" }

planning_new:
    pattern:  /new
    defaults: { _controller: "CaravaneOrganicBundle:Planning:new" }

planning_create:
    pattern:  /create
    defaults: { _controller: "CaravaneOrganicBundle:Planning:create" }
    requirements: { _method: post }

planning_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CaravaneOrganicBundle:Planning:edit" }

planning_update:
    pattern:  /{id}/update
    defaults: { _controller: "CaravaneOrganicBundle:Planning:update" }
    requirements: { _method: post }

planning_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CaravaneOrganicBundle:Planning:delete" }
    requirements: { _method: post }
