tent:
    pattern:  /
    defaults: { _controller: "CaravaneOrganicBundle:Tent:index" }
    options:
        expose: true

tent_show:
    pattern:  /{id}/show
    defaults: { _controller: "CaravaneOrganicBundle:Tent:show" }

tent_new:
    pattern:  /new
    defaults: { _controller: "CaravaneOrganicBundle:Tent:new" }

tent_create:
    pattern:  /create
    defaults: { _controller: "CaravaneOrganicBundle:Tent:create" }
    requirements: { _method: post }

tent_export:
    pattern:  /export
    defaults: { _controller: "CaravaneOrganicBundle:Tent:export" }

tent_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CaravaneOrganicBundle:Tent:edit" }

tent_update:
    pattern:  /{id}/update
    defaults: { _controller: "CaravaneOrganicBundle:Tent:update" }
    requirements: { _method: post }

tent_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CaravaneOrganicBundle:Tent:delete" }
    requirements: { _method: post }

tent_get_available:
    pattern: /get_available
    defaults: { _controller: "CaravaneOrganicBundle:Tent:getAvailableFromRoute" }
    requirements: { _method: get }
    options:
        expose: true

tent_remove_document:
    pattern:  /{id}/remove_document/{documentid}
    defaults: { _controller: "CaravaneOrganicBundle:Tent:removeDocument" }
    requirements: { _method: post }
    options:
        expose: true

